#ifndef ALX_BUILD_GENERATED_H
#define ALX_BUILD_GENERATED_H


#define ALX_BUILD_NAME "VisualGDB Local"
#define ALX_BUILD_DATE 2405291222
#define ALX_BUILD_NUM 0
#define ALX_BUILD_HASH "abcdefabcdefabcdefabcdefabcdefabcdefabcd"
#define ALX_BUILD_HASH_SHORT "abcdefa"
#define ALX_BUILD_HASH_SHORT_UINT32 0x0ABCDEFA
#define ALX_BUILD_REV 0
#define ALX_BUILD_FW_VER_MAJOR 255
#define ALX_BUILD_FW_VER_MINOR 255
#define ALX_BUILD_FW_VER_PATCH 255


#endif	// ALX_BUILD_GENERATED_H
